# Generated by Django 4.0.3 on 2022-03-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Имя клиента')),
                ('phone', models.CharField(max_length=300, verbose_name='Телефон клиента')),
                ('email', models.CharField(max_length=1000, verbose_name='Почта клиента')),
            ],
            options={
                'verbose_name': 'Форма обратной связи',
                'verbose_name_plural': 'Форма обратной связи',
            },
        ),
    ]
